name: builder
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 texlive texlive-latex-extra texlive-bibtex-extra biber

      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            python3 .github/workflows/build.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: build/samples/*/*.pdf
